### ISSUE TITLE
How to handle parametric Unitful types

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/Arrow.jl#139]
I don't see how to handle parametric Unitful types in general. The type of the object is determined at runtime to be something like

```jl
Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,Unitful.Affine{-5463//20}}}
```
so I don't know how to register it in the writer or reader.

```jl
using DataFrames, Arrow, Unitful, Unitful.DefaultSymbols
using Unitful: Ra

let t = Quantity{Float64,𝚯,Unitful.FreeUnits{(Ra,),𝚯,Unitful.Affine}}
    Arrow.ArrowTypes.registertype!(t, t)
end
data = Dict(:col => rand(10) .* u"°C")

Arrow.write("/tmp/example.arrow", data)
```

```jl
using DataFrames, Arrow, Unitful, Unitful.DefaultSymbols
using Unitful: Ra

let t = Quantity{Float64,𝚯,Unitful.FreeUnits{(Ra,),𝚯,Unitful.Affine}}
    Arrow.ArrowTypes.registertype!(t, t)
end

show(Arrow.Table("/tmp/example.arrow"))
```

```
┌ Warning: unsupported ARROW:extension:name type: "JuliaLang.Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,Unitful.Affine{-5463//20}}}"
└ @ Arrow.ArrowTypes ~/.julia/packages/Arrow/Re9EM/src/arrowtypes.jl:174
Arrow.Table:
 :col  NamedTuple{(:val,),Tuple{Float64}}[(val = 0.6815439614007792,), (val = 0.04956826502952305,), (val = 0.6934042584270963,), (val = 0.8354521302501914,), (val = 0.9176167864760512,), (val = 0.8196385683137586,), (val = 0.4645637742765887,), (val = 0.25589311520695124,), (val = 0.9277780364437311,), (val = 0.05186865321486933,)]
```

```
  [69666777] Arrow v1.2.4
  [1986cc42] Unitful v1.5.0
```

**Comment by quinnj** [comment]
Ok, sorry about the hassle here. So here's what's going on:
* You are indeed registering a type, but it's actually _slightly different_ from the actual custom type that gets serialized. You can see this w/:

```julia
julia> a = Quantity{Float64,𝚯,Unitful.FreeUnits{(Ra,),𝚯,Unitful.Affine}}
Quantity{Float64, 𝚯, Unitful.FreeUnits{(Ra,), 𝚯, Unitful.Affine}}

julia> b = eltype(data[:col])
Quantity{Float64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, Unitful.Affine{-5463//20}}}
```
Note the difference in the `UnitFul.Affine`.

* So then the issue is that Arrow will auto-register concrete custom structs, so the `eltype(data[:col])` gets registered and is actually stored with the arrow column metadata
* Reading then fails because it doesn't have the _exact same_  type registered, so the more correct flow to do what you're doing here is something like:

writing:
```julia
using Arrow, Unitful, Unitful.DefaultSymbols
using Unitful: Ra

# don't need to register since it will be auto-registered
data = Dict(:col => rand(10) .* u"°C")

Arrow.write("/tmp/example.arrow", data)
```

reading:
```julia
using Arrow, Unitful, Unitful.DefaultSymbols
using Unitful: Ra

let t = typeof(rand() * u"°C")
    Arrow.ArrowTypes.registertype!(t, t)
end

show(Arrow.Table("/tmp/example.arrow"))
```

If you have any suggestions on improvements to the documentation, I'd really appreciate it.

**Comment by jmtlawrie** [comment]
Hello!

First off please let me say that I've been enjoying getting to know about Apache Arrow and Arrow.jl and have had a very positive experience so far; thank you for taking the time to provide this resource to the Julia community!

Is it correct that the function `registertype` has been depreciated since this original post (please see snippet below)?

If so, would it be appropriate to open a new issue regarding the serialization of data featuring`Unitful.jl` types to the `.arrow` format, since the approach here is no longer available?
* This afternoon I successfully followed the [helpful examples](https://apache.github.io/arrow-julia/stable/manual/#Custom-types) provided in the user manual and reproduced their results as expected, but I got a bit stuck with following the examples and applying them successfully to `Unitful` types.

```
julia> using Arrow

help?> Arrow.ArrowTypes.registertype!
  No documentation found.

  Binding ArrowTypes.registertype! does not exist.
```

Thank you in advance!

jmtlawrie

----
```
(@v1.9) pkg> st Arrow
Status `~/.julia/environments/v1.9/Project.toml`
  [69666777] Arrow v2.6.2

julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 4 × Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, broadwell)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
```
