### ISSUE TITLE
Reading CSV

### ISSUE THREAD

**Issue by calebwin** [JuliaData/Arrow.jl#157]
Maybe I'm missing something obvious.. but is there a way to read a CSV file (e.g., a `CSV.File`) into an `Arrow.Table`?

**Comment by quinnj** [comment]
Sure thing. The one thing to remember is that the arrow spec is a specific _memory_ layout. An `Arrow.Table` is a Julia object that acts as a "view" into that arrow memory, so in order to have a `Arrow.Table`, we need that arrow memory somewhere first. You could write the data out to an arrow-formatted file, like `tbl = Arrow.Table(Arrow.write("data.arrow", csv_file))`, or you could keep the data in-memory, for which Arrow.jl provides a convenience function like `tbl = Arrow.Table(Arrow.tobuffer(csv_file))`.
