### ISSUE TITLE
CategoricalArrays strikes again

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Arrow.jl#2]
I think we should handle this:
```
julia> df = DataFrame(x6=categorical(["a","b"]), x7=categorical(["a",missing]))
2×2 DataFrame
│ Row │ x6   │ x7      │
│     │ Cat… │ Cat…?   │
├─────┼──────┼─────────┤
│ 1   │ a    │ a       │
│ 2   │ b    │ missing │

julia> Arrow.write("test.arrow", df)
ERROR: MethodError: no method matching arrowtype(::Arrow.FlatBuffers.Builder, ::Type{CategoricalValue{String,UInt32}})
```

**Comment by quinnj** [comment]
Ok, so the half-baked sketch in my mind is to use `DataAPI.refarray` on input columns since we can use that + `DataAPI.refpool` to write the arrow column directly (since that's how you write "dict encoded" columns anyway). Obviously need to work out the implementation details here, but I think that should work w/o requiring a dependency on PooledArrays/CategoricalArrays.

**Comment by bkamins** [comment]
That would be ideal. I hope that if we can get it here then we can drop the dependency on CategoricalArrays.jl in `groupby`/joins in a similar manner (maybe some extra trait in DataAPI.jl will be required - not sure, as I do not know the design there in all details)

**Comment by quinnj** [comment]
Ok, so I have the approach with using `refarray`/`refpool` working locally; now we just need CategoricalArrays to actually define `refarray`/`refpool` 😛

**Comment by quinnj** [comment]
Here's `refarray`/`refpool` for CategoricalArrays.jl that allows using Arrow.jl w/o problems: https://github.com/JuliaData/CategoricalArrays.jl/pull/297

**Comment by quinnj** [comment]
This is closed becaues the support in Arrow.jl is done; but obviously still needs the CategoricalArrays.jl PR to make it work w/ CategoricalArrays
