### ISSUE TITLE
`pyarrow` unable to load Arrow data written by `Arrow.jl`

### ISSUE THREAD

**Issue by rgankema** [JuliaData/Arrow.jl#261]
I tried serializing some data and writing it to disk using the `Arrow.jl` library today, but I was unable to then deserialize it using the `pyarrow` library. Here's an MRE:

Writing the file:
```julia
open("test.arrow", "w") do f
    Arrow.write(f, (a=[1,2,3], b=[4,5,6]))
end
```

Loading the file:
```python
>>> pd.read_feather("test.arrow")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pandas/io/feather_format.py", line 130, in read_feather
    return feather.read_feather(
  File "/usr/local/lib/python3.9/site-packages/pyarrow/feather.py", line 220, in read_feather
    return (read_table(source, columns=columns, memory_map=memory_map)
  File "/usr/local/lib/python3.9/site-packages/pyarrow/feather.py", line 241, in read_table
    reader = _feather.FeatherReader(source, use_memory_map=memory_map)
  File "pyarrow/_feather.pyx", line 75, in pyarrow._feather.FeatherReader.__cinit__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Not a Feather V1 or Arrow IPC file
```

Loading that same file with `Arrow.Table` works just fine:

```julia
julia> Arrow.Table("test_vec.arrow")
Arrow.Table with 3 rows, 2 columns, and schema:
 :a  Int64
 :b  Int64

julia> Arrow.Table("test_vec.arrow").a
3-element Arrow.Primitive{Int64, Vector{Int64}}:
 1
 2
 3
 ```
 
 Did I do something wrong while serializing that table to Arrow, or is this a bug? If it's the latter, I'm not sure if it's on the `Arrow.jl` or `pyarrow` side, but as a Julia user I thought I'd ask here first :) Thanks!

**Comment by quinnj** [comment]
@rgankema, thanks for reporting. So the issue here is a little subtle and I'd love to hear ideas on how we can improve the documentation here: when you pass an `IO` object (like `IOStream` in your example), `Arrow.write` will just write any record batches of the input table "as is", that is, as straight "record batches". In pyarrow parlance, you would then want to use the `pyarrow.ipc.open_stream`-family of functions, which operate on streams of record batches.

If, however, you were to change your example to:
```julia
Arrow.write("test.arrow", (a=[1,2,3], b=[4,5,6]))
```
Then `Arrow.write` assumes you actually want to write the additional metadata as a proper "IPC file", which can then be read as-is by `pd.read_feather`. There is still a way to get the "file-writing" behavior in your original example, and that's by passing `file=true` keyword argument, like:
```julia
open("test.arrow", "w") do f
    Arrow.write(f, (a=[1,2,3], b=[4,5,6]); file=true)
end
```
That tells `Arrow.write` explicitly that you want to write the IPC file format instead of just raw record batches.

Hope that helps explain a little what is going on! Again, if you have suggestions on how to improve our docs, it would probably be helpful for others if we were able to clarify what's going on here for future users.

**Comment by rgankema** [comment]
Thanks, that's very helpful! And sorry, it seems like all of this was already in the `Arrow.write` documentation so I should have done a better job of reading the docs. I do think it could be a little more clear if this information was also added to the [manual](https://arrow.juliadata.org/dev/manual/#Arrow.write).

**Comment by NHDaly** [comment]
👍 thanks both for the very clear discussion. :) We were also trying to parse the arrow from Python, and we independently ran into the same thing 😁 😅 

+1 for adding a note about this to the User Manual. Maybe we can also link to some Apache arrow documentation that describes what the difference is between a File and a Stream? I think this document seems like a good reference: https://arrow.apache.org/docs/python/ipc.html - are there any others you would suggest in addition / instead, @quinnj? Thanks!
