### ISSUE TITLE
No error when writing NamedTuple "table" with different-length columns

### ISSUE THREAD

**Issue by kcajf** [JuliaData/Arrow.jl#60]
```
julia> b = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> Arrow.write(b, (;a = Int[], b = ["asd"], c=collect(1:100)))
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=1296, maxsize=Inf, ptr=1297, mark=-1)

julia> Arrow.Table(seekstart(b))
Arrow.Table: (a = Int64[], b = ["asd"], c = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10  …  91, 92, 93, 94, 95, 96, 97, 98, 99, 100])
```
I'm surprised that this roundtrips fine. Should there be an error if a table's columns have different lengths, both when reading and writing? Or is this allowable in the Arrow spec (curious what the usecase would be)?

**Comment by quinnj** [comment]
It's not specifically mentioned in the spec, but I've confirmed that other implementations have a validity check on this. The problem is that the RecordBatch should have a single `numrows` field that applies to each column in the batch. But then when serializing/deserializing each column, you use the # bytes / sizeof eltype to compute the # of elements to deserialize (which is why it currently works). I'll add a validity check.

**Comment by quinnj** [comment]
PR up: https://github.com/JuliaData/Arrow.jl/pull/65

**Comment by kcajf** [comment]
That makes sense, thanks for fixing.
