### ISSUE TITLE
Releasing the lock on arrow file

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Arrow.jl#61]
When you read the file using `Arrow.Table` then a lock on the file is made. I could not find a function to release the lock within a session on Windows.
The only way that works is doing:
1. removing all references to the table.
2. doing `GC.gc()`
3. then you can remove the file

This is valid and makes sense, but the question is if there is some other way to do it (maybe not).

If not then I understand that the recommended pattern for such cases is to open file, pass IO to `ArrowTable`, and close file. Is this correct and recommended pattern if you want to avoid memory mapping and locking the file?

This is needed in the scenarios when you want to use Arrow as a temporary storage on disk but want to clean up things after the session.

(I am writing a blog post on Arrow.jl now)

**Comment by quinnj** [comment]
Yes, that is currently the correct way to release the file lock for windows (due to mmaping). We could add a finalizer on `Arrow.Table` that also finalized the underlying buffer, which would mean you could just do `finalize(table)` and the lock would be released (though the `table` would then be invalid). I can look into doing that.

**Comment by bkamins** [comment]
Thank you. I think there is no rush with the finalizer. I just wanted to make sure that I correctly understand the current design.
